name: CD

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
    - uses: actions/setup-node@master

    - name: npm install
      run: npm install
      working-directory: /home/runner/work/stopwatch/stopwatch

    - name: Compile
      run: npm run build:prod
      working-directory: /home/runner/work/stopwatch/stopwatch
    
    - name: Build Docker image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: accendit/stopwatch/stopwatch
        registry: docker.pkg.github.com
        username: Accendit
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_names: true